#!/usr/bin/env bash
set -euo pipefail
ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FLOORSET_COMMIT="aadddcc2238695eb21e6542b8a6cd9e9fe6b80fa"
cd "$ROOT"
if [ ! -d external/FloorSet ]; then
  mkdir -p external
  git clone https://github.com/IntelLabs/FloorSet.git external/FloorSet
  git -C external/FloorSet checkout --detach "$FLOORSET_COMMIT"
elif [ "$(git -C external/FloorSet rev-parse HEAD)" != "$FLOORSET_COMMIT" ]; then
  echo "ERROR: external/FloorSet is not pinned at $FLOORSET_COMMIT" >&2
  echo "Use a clean checkout at that commit before evaluating." >&2
  exit 1
fi
python3 -m venv .venv
# The activation file is generated by the command immediately above.
# shellcheck disable=SC1091
. .venv/bin/activate
pip install --upgrade "pip==26.1.2"
# Install the official contest dependencies (torch, numpy, shapely, matplotlib,
# tqdm, requests) plus pytest, rather than an ad-hoc list.
pip install -r external/FloorSet/iccad2026contest/requirements.txt pytest
cp contest_solution/my_optimizer.py external/FloorSet/iccad2026contest/my_optimizer.py
cp contest_solution/dissect.py external/FloorSet/iccad2026contest/dissect.py
cp contest_solution/topology_polish.py external/FloorSet/iccad2026contest/topology_polish.py
cp contest_solution/sequence_pair_sa.py external/FloorSet/iccad2026contest/sequence_pair_sa.py
cp contest_solution/test_my_optimizer.py external/FloorSet/iccad2026contest/test_my_optimizer.py
cd external/FloorSet
PYTHONPATH=. python lite_dataset_test.py
cd iccad2026contest
PYTHONPATH=.. ../../../.venv/bin/python -m pytest test_my_optimizer.py -q
PYTHONPATH=.. ../../../.venv/bin/python iccad2026_evaluate.py --validate my_optimizer.py
mkdir -p "$ROOT/results"
OUTPUT="${OUTPUT:-$ROOT/results/setup_evaluation.json}"
PYTHONPATH=.. ../../../.venv/bin/python iccad2026_evaluate.py --evaluate my_optimizer.py --verbose --save-solutions --output "$OUTPUT"
cd "$ROOT"
python scripts/audit_results.py "$OUTPUT" --expected-cases 100 --require-positions
